---
- name: Install Nix
  when: install_nix|bool
  tags:
      - nix
  import_tasks: nix.yml

- name: Install Nix packages
  tags:
      - nix
  import_tasks: nixpkgs.yml

- name: Bootstrap Git-Credential-Manager (github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux)
  tags:
      - packages
      - gcm
  when: install_gcm|bool
  import_tasks: gcm.yml

- name: Install Linuxbrew  # BSD 2-clause
  tags:
      - packages
      - brew
      - homebrew
      - linuxbrew
  import_tasks: linuxbrew.yml
  when: install_homebrew|bool

- name: Install packages & other software
  tags:
      - packages
      - brew
      - homebrew
      - linuxbrew
  import_tasks: managers.yml

- name: Install PowerShell
  tags:
    - packages
    - powershell
    - pwsh
    - microsoft
  import_tasks: powershell.yml

- name: Install Fish plugins
  tags:
      - fish
      - packages
  import_tasks: fish.yml

- name: Install Tmux plugins
  tags:
      - tmux
      - packages
  import_tasks: tmux.yml

- name: Install Rust  # Apache 2.0 & MIT (dual-licensed)
  when: install_rust|bool
  tags:
      - packages
      - rust
  import_tasks: rust.yml

- name: Install Rust  # Apache 2.0 & MIT (dual-licensed)
  when: install_rust|bool
  tags:
      - packages
      - rust
      - cargo
  import_tasks: cargo.yml

- name: Install Talisman (github.com/thoughtworks/talisman)  # MIT
  when: install_talisman|bool
  tags:
      - packages
      - talisman
  import_tasks: talisman.yml

- name: Install alacritty (github.com/jwilm/alacritty)
  when: install_alacritty|bool
  tags:
      - packages
      - gui
      - alacritty
  import_tasks: alacritty.yml

- name: Install TeX Live
  when: install_texlive|bool
  tags:
      - packages
      - tex
      - texlive
      - tex-live
  become: true
  apt:
      package: texlive

- name: Install MikTeX
  when: install_miktex|bool
  tags:
      - packages
      - tex
      - miktex
  import_tasks: miktex.yml

- name: Install haskell-stack
  tags:
      - haskell
      - ghc
      - stack
      - haskell-stack
  import_tasks: haskell-stack.yml

- name: Install haskell cabal tools
  tags:
      - haskell
      - ghc
      - cabal
      - cabal-install
  import_tasks: haskell-cabal.yml

- name: Install haskell-ide-engine
  tags:
      - haskell
      - hie
      - ghc
      - stack
      - haskell-ide-engine
  import_tasks: haskell-ide-engine.yml
