---
- name: Add Nightly Rust
  register: rustup_nightly
  changed_when: >-
    'installing' in rustup_nightly.stdout
  command: >-
      {{ nix_bins }}/rustup toolchain add nightly

- name: Upgrade Rust
  command: '{{ nix_bins }}/rustup update'
  register: rustup_update
  changed_when: >-
    'installing' in rustup_update.stdout

- name: Ensure Rust components are up-to-date
  loop:
    - cargo
    - clippy
    - rust-docs
    - rust-src
    - rustfmt
    - rls
    - rust-analysis
  command: '{{ nix_bins }}/rustup component add {{ item }}'
  register: rustup_component
  changed_when: >-
    'installing' in rustup_component.stdout
