---
- name: Check for Talisman pre-commit hook
  register: talisman_grep
  command: grep talisman {{ pre_commit_tpl }}
  # rc=2 => file not found
  failed_when: talisman_grep.rc not in [0, 1, 2]
  changed_when: talisman_grep.rc in [1, 2]

- name: Install github.com/thoughtworks/talisman
  when: talisman_grep is changed
  block:
    - name: Create temporary file
      register: tmp_bash
      tempfile:
          suffix: .bash

    - name: Download Talisman
      get_url:
          url: '{{ talisman_url }}'
          dest: '{{ tmp_bash.path }}'

    - name: Install Talisman
      shell: "yes '\n' | bash {{ tmp_bash.path }}"
