---
# Software that's not in a package manager.

install_nix: true
nix_profile: '{{ ansible_user_dir }}/.nix-profile/'
nix_bins: '{{ nix_profile }}/bin/'
nix_env_bin: '{{ nix_bins }}/nix-env'

npm_install_become: true
npm_bin: '{{ nix_bins }}/npm'

# https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux
# use gcm during the dotfiles and vimfiles git repo cloning?
bootstrap_gcm: true

# install gcm separately
install_gcm: false
gcm_version: 2.0.4
gcm_dest: '{{ local_prefix }}/bin/git-credential-manager-{{ gcm_version }}.jar'
gcm_shim_dest: '{{ local_prefix }}/bin/git-credential-manager'
gcm_url: >-
    https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux
    {#-#}/releases/download/git-credential-manager-{{ gcm_version -}}
    /git-credential-manager-{{ gcm_version }}.jar

# https://forge.rust-lang.org/infra/other-installation-methods.html
install_rust: true
rustup_arch: x86_64-unknown-linux-gnu
rustup_url: https://static.rust-lang.org/rustup/dist/{{ rustup_arch }}/rustup-init
cargo_bin_dir: '{{ ansible_user_dir }}/.cargo/bin'
cargo_bin: '{{ cargo_bin_dir }}/cargo'

fish_version: 3.0.2
fish_bin: '{{ nix_bins}}/fish'
fisher_url: https://git.io/fisher
fisher_dir: '{{ ansible_user_dir }}/.config/fish/functions'
fisher: '{{ fisher_dir }}/fisher.fish'

# https://github.com/thoughtworks/talisman
install_talisman: true
talisman_url: https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/install.bash
pre_commit_tpl: '{{ ansible_user_dir }}/.git-template/hooks/pre-commit'

tpm: '{{ ansible_user_dir }}/.tmux/plugins/tpm'
tpm_url: https://github.com/tmux-plugins/tpm

install_hexd: false
install_pixd: false

# https://miktex.org/
install_texlive: false
install_miktex: true
miktex_gpg_key: D6BC243565B2087BC3F897C9277A7293F59E4889
miktex_apt_repo: deb http://miktex.org/download/ubuntu bionic universe
miktex_mpm_bin: /usr/bin/mpm

# Options: 'essential', 'basic', 'complete'
miktex_package_level: basic
user_texmf_root: '{{ ansible_user_dir }}/.miktex/texmfs/install'

install_alacritty: false
alacritty_url: https://github.com/jwilm/alacritty.git

rebeccastyle_repo:
    git: https://github.com/9999years/rebeccaessay
    dest: '{{ ansible_user_dir }}/projects/rebeccastyle'

microsoft_deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
