---
apt_packages_skip: []
apt_packages_extra: []

apt_packages_essential:
      # editors
    - neovim  # Apache 2.0
      # shell utilities / dev tools
    - build-essential
    - tmux  # ISC License
    - silversearcher-ag  # Apache 2.0
    - colordiff  # GPL v3
    - colortest
    - source-highlight  # GPL v3
    - pandoc  # GLP v2+ & BSD 3-clause & MIT & WTFPL (dzslides)
    - sshfs  # GPL v2
    - lftp  # GPL v3+
      # git
    - git  # GPL v2
    - git-lfs  # MIT
      # programming languages
    - openjdk-11-jdk  # GPL v2
    - ruby  # BDS 2-clause
    - ruby-dev

apt_packages:
      # editors
    - vim  # GPL-compatible
    # - vim-gtk
      # shell utilities / dev tools
    - linuxbrew-wrapper
    - shellcheck  # GPL v3
    - cloc  # GPL v2 & Artistic License
    - ghostscript
    - imagemagick  # Derived Apache 2.0
    - graphviz  # CPL 1.0
    - toilet  # command-line ascii art generator
    - libclang-dev  # 0.5gb :(
    - zlib1g-dev  # Required for cargo-update
    # - reptyer
    # - pdftk
      # git
    - gitk
    - tig
      # programming languages
    - ghc
    - cabal-install
    - perl
    - golang

install_homebrew: true
homebrew_install: https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh
homebrew_root: /home/linuxbrew/.linuxbrew
homebrew_bin: '{{ homebrew_root }}/Homebrew/bin/brew'
homebrew_bin_dir: '{{ homebrew_root }}/bin'

homebrew_packages:
    - git-credential-manager  # MIT
    - fish  # GPL v2 & LGPL v2, OpenBSD License, ISC, NetBSD
    - python  # GPL-compatible PSF; https://docs.python.org/3/license.html
    - fzf  # MIT
    - jq  # MIT
    - hub  # MIT
    - nvim
    - just  # github.com/casey/just

homebrew_packages_extra: []
homebrew_packages_skip: []

homebrew_links:
    - git-credential-manager
    - fish
    - python3
    - python3.7
    - pip3
    - pip3.7
    - just

pip_bin: '{{ homebrew_bin_dir }}/pip3'
pip_packages:
    - Pillow
    - PyYAML
    - Pygments
    - arrow
    - atomicwrites
    - attrs
    - beautifulsoup4
    - black
    - cached-property
    - cachetools
    - colorama
    - grip
    - more-itertools
    - mypy
    - neovim
    - numba
    - numpy
    - pep8
    - ptpython
    - pycodestyle
    - pylint
    - pynvim
    - pytest
    - python-dateutil
    - python-decouple
    - requests
    - termcolor
    - toml
    - unidecode
    - urllib3
    - virtualenv
    - wcwidth
    - youtube-dl
    - vim-vint  # vimscript lint: https://github.com/Kuniwak/vint

ruby_gems:
    - neovim  # MIT
    - uniscribe  # MIT

npm_packages:  # node_packages
    - npm
    - neovim  # MIT
    - typescript  # Apache 2.0
    - babel-cli  # MIT
    - webpack  # MIT
    - hexo-cli  # MIT
    - yarn
    - prettier
    - markdownlint-cli
    - write-good

npm_packages_skip: []
npm_packages_extra: []

cabal_packages_skip: []
cabal_packages_extra: []
cabal_packages:
  - happy  # required by other stuff, don't remove.
  - pointfree
  - hlint
  - apply-refact
  - hspec
  - hindent

stack_packages_skip: []
stack_packages_extra: []
stack_packages:
  - hdevtools
  - stylish-haskell

stack_global_extra_deps: |
  extra-deps:
    - haskell-src-exts-1.20.3@sha256:83ae523bbec907a42c043de1f5bbf4c1554e7c3b898af07bb1ce6e80eaa282ec,4589

# https://github.com/rust-unofficial/awesome-rust#applications
cargo_packages:
  - --git https://github.com/darakian/ddh ddh
  - --git https://github.com/lotabout/rargs rargs
  # cat(1) clone with syntax highlighting, prints non-printing characters with
  # -A, git integration, etc.
  # https://github.com/sharkdp/bat
  - bat  # requires libclang-dev
  # Binary introspection
  # https://github.com/m4b/bingrep
  - bingrep
  # "exa is a replacement for ls written in Rust."
  # https://github.com/ogham/exa
  - exa
  # "The next gen ls command"
  # https://github.com/Peltoche/lsd
  - lsd
  # "Find files with SQL-like queries"
  # https://github.com/jhspetersson/fselect
  - fselect
  # "Yet another fancy watcher. (Inspired by antr / entr)"
  # "Configure execution of different commands using semantic yaml."
  # https://github.com/cristianoliveira/funzzy
  - funzzy
  # "With fw you have a configuration describing your workspace. It takes care
  # of cloning projects and can run commands across your entire workspace. You
  # can start working on any project quickly, even if it’s not in your flat
  # structured workspace"
  # https://github.com/brocode/fw
  - fw
  # Hexdump
  # https://github.com/sitkevij/hex
  - hx
  # CLI benchmarker
  # https://github.com/sharkdp/hyperfine
  - hyperfine
  # Faster grep.
  # https://github.com/BurntSushi/ripgrep
  - ripgrep  # rg
  # - runiq  # requires cmake
  - ruplacer
  # Find-and-replacer
  # https://github.com/chmln/sd
  - sd
  # "Find Files (ff) utility recursively searches the files whose names match
  # the specified RegExp pattern in the provided directory (defaults to the
  # current directory if not provided)."
  # https://github.com/vishaltelangre/ff
  - find-files
  # Fuzzy finder
  # https://github.com/lotabout/skim
  - skim
  # Cloc
  # https://github.com/XAMPPRocky/tokei
  - tokei
  # CSV data manipulation and analysis tool.
  # https://github.com/BurntSushi/xsv
  - xsv
  # Generates a dep graph
  # https://github.com/m-cat/cargo-deps
  - cargo-deps
  # This tool extends Cargo to allow you to add, remove, and upgrade
  # dependencies by modifying your Cargo.toml file from the command line.
  # https://github.com/killercup/cargo-edit
  - cargo-edit
  # https://github.com/sagiegurari/cargo-make
  - cargo-make
  # - cargo-modules  Requires nightly to *run* as of 0.4.4
  # "displays when newer versions of Rust dependencies are available, or out of
  # date"
  # https://github.com/kbknapp/cargo-outdated
  - --git https://github.com/kbknapp/cargo-outdated
  # https://github.com/sunng87/cargo-release
  - cargo-release
  # Dep tree.
  # https://github.com/sfackler/cargo-tree
  - cargo-tree
  # Updates deps.
  # https://github.com/nabijaczleweli/cargo-update
  - cargo-update
  # Watches source files.
  # https://github.com/passcod/cargo-watch
  - cargo-watch
  # Broken as of 2019-10-08.
  # https://github.com/racer-rust/racer
  # - toolchain: nightly
    # crate: racer
