---
apt_packages_skip: []
apt_packages_extra: []

apt_packages_essential:
    - build-essential

apt_packages:
    - libssl-dev  # Required for fw

install_homebrew: false
homebrew_install: https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh
homebrew_root: /home/linuxbrew/.linuxbrew
homebrew_bin: '{{ homebrew_root }}/Homebrew/bin/brew'
homebrew_bin_dir: '{{ homebrew_root }}/bin'

homebrew_packages:
    - git-credential-manager  # MIT

homebrew_packages_extra: []
homebrew_packages_skip: []

homebrew_links:
    - git-credential-manager

nix_channels:
  - url: 'https://hydra.dhall-lang.org/jobset/dhall-haskell/master/channel/latest'
    name: dhall-haskell-master-latest
nix_packages:
    - nixpkgs.python38Full
    # Linters, etc.
    - nixpkgs.python38Packages.pip
    - nixpkgs.python38Packages.setuptools
    - nixpkgs.python38Packages.virtualenv
    - nixpkgs.python38Packages.pytest
    - nixpkgs.python38Packages.black
    - nixpkgs.python38Packages.grip
    - nixpkgs.python38Packages.mypy
    - nixpkgs.python38Packages.flake8
    - nixpkgs.python38Packages.ptpython
    - nixpkgs.python38Packages.pycodestyle
    - nixpkgs.python38Packages.pylint
    # Utilities
    - nixpkgs.python38Packages.pillow
    - nixpkgs.python38Packages.pyyaml
    - nixpkgs.python38Packages.pygments
    - nixpkgs.python38Packages.arrow
    - nixpkgs.python38Packages.atomicwrites
    - nixpkgs.python38Packages.attrs
    - nixpkgs.python38Packages.beautifulsoup4
    - nixpkgs.python38Packages.cached-property
    - nixpkgs.python38Packages.cachetools
    - nixpkgs.python38Packages.colorama
    - nixpkgs.python38Packages.more-itertools
    - nixpkgs.python38Packages.numpy
    - nixpkgs.python38Packages.pynvim
    - nixpkgs.python38Packages.dateutil
    # - nixpkgs.python38Packages.python-decouple
    - nixpkgs.python38Packages.requests
    - nixpkgs.python38Packages.termcolor
    - nixpkgs.python38Packages.toml
    - nixpkgs.python38Packages.unidecode
    - nixpkgs.python38Packages.urllib3
    - nixpkgs.python38Packages.virtualenv
    - nixpkgs.python38Packages.wcwidth

    - nixpkgs.gitAndTools.gitFull  # GPL v2
    - nixpkgs.git-lfs  # MIT
    - nixpkgs.gitAndTools.hub  # github hub, MIT
    - nixpkgs.gitAndTools.diff-so-fancy
    - nixpkgs.bfg-repo-cleaner

    - nixpkgs.fish  # GPL v2 & LGPL v2, OpenBSD License, ISC, NetBSD
    - nixpkgs.neovim
    - nixpkgs.tmux  # ISC License

    - nixpkgs.silver-searcher
    - nixpkgs.fzf  # MIT
    - nixpkgs.jq  # MIT
    - nixpkgs.exa
    - nixpkgs.just  # github.com/casey/just
    - nixpkgs.topgrade
    - nixpkgs.bat  # https://github.com/sharkdp/bat
    - nixpkgs.bingrep # Binary introspection, https://github.com/m4b/bingrep
    - nixpkgs.fselect # "Find files with SQL-like queries" https://github.com/jhspetersson/fselect
    - nixpkgs.hyperfine
    - nixpkgs.ruplacer
    - nixpkgs.ripgrep  # rg, https://github.com/BurntSushi/ripgrep
    - nixpkgs.ripgrep-all
    - nixpkgs.sd # Find-and-replacer, https://github.com/chmln/sd
    - nixpkgs.skim # Fuzzy finder, https://github.com/lotabout/skim
    - nixpkgs.tokei # Cloc, https://github.com/XAMPPRocky/tokei
    - nixpkgs.xsv # CSV data manipulation and analysis tool, https://github.com/BurntSushi/xsv

    - nixpkgs.rustup
    - nixpkgs.cargo-deps # Generates a dep graph, https://github.com/m-cat/cargo-deps
    - nixpkgs.cargo-edit # https://github.com/killercup/cargo-edit
    - nixpkgs.cargo-update # https://github.com/nabijaczleweli/cargo-update
    - nixpkgs.cargo-watch # Watches source files, https://github.com/passcod/cargo-watch
    - nixpkgs.cargo-tree # Dep tree. https://github.com/sfackler/cargo-tree
    - nixpkgs.cargo-release # https://github.com/sunng87/cargo-release
    - nixpkgs.cargo-outdated # https://github.com/kbknapp/cargo-outdated
    - nixpkgs.cargo-make # https://github.com/sagiegurari/cargo-make

    - nixpkgs.stylish-haskell
    - nixpkgs.hlint
    - nixpkgs.haskellPackages.happy
    - nixpkgs.haskellPackages.pointfree
    - nixpkgs.haskellPackages.apply-refact
    # - nixpkgs.haskellPackages.hie-core  # broken 2019-12-21
    - nixpkgs.haskellPackages.hspec
    - nixpkgs.haskellPackages.hindent
    - nixpkgs.haskellPackages.hdevtools

    - nixpkgs.solargraph  # ruby LSP
    - nixpkgs.vim-vint  # vimscript lint: https://github.com/Kuniwak/vint
    - nixpkgs.youtube-dl
    - nixpkgs.sshfs-fuse  # GPL v2
    - nixpkgs.lftp  # GPL v3+
    - nixpkgs.pandoc  # GLP v2+ & BSD 3-clause & MIT & WTFPL (dzslides)
    - nixpkgs.colordiff  # GPL v3
    - nixpkgs.sourceHighlight  # GPL v3

    - nixpkgs.clang
    # - nixpkgs.llvmPackages.libclang
    - nixpkgs.clang-tools
    - nixpkgs.clang-analyzer

    - nixpkgs.ruby  # BDS 2-clause
    - nixpkgs.openjdk
    - nixpkgs.shellcheck
    - nixpkgs.ghostscript
    - nixpkgs.imagemagick7Big  # Derived Apache 2.0
    - nixpkgs.graphviz
    - nixpkgs.toilet  # command-line ascii art generator
    - nixpkgs.reptyr
    - nixpkgs.tig  # git text-gui
    - nixpkgs.ghc
    - nixpkgs.cabal-install
    - nixpkgs.stack
    - nixpkgs.go
    - nixpkgs.pdftk
    - nixpkgs.perl  # If nothing else, latexmk needs it.

    - nixpkgs.alacritty
    - nixpkgs.fd
    - nixpkgs.nodejs-13_x
    - nixpkgs.tree

    - nixpkgs.dhall
    - nixpkgs.dhall-bash
    - nixpkgs.dhall-json

    - nixpkgs.zlib  # For pip Pillow

    # - dhall-haskell-master-latest.linux-dhall
    # - dhall-haskell-master-latest.linux-dhall-bash
    # - dhall-haskell-master-latest.linux-dhall-json
    # - dhall-haskell-master-latest.linux-dhall-lsp-server
    # - dhall-haskell-master-latest.linux-dhall-nix
    # - dhall-haskell-master-latest.linux-dhall-yaml

pip_bin: '{{ nix_bins }}/pip3'
pip_packages:
    - python-decouple

ruby_gems:
    - bundler
    - neovim  # MIT
    - uniscribe  # MIT
    - solargraph  # Ruby LSP
    # - sorbet-static  # Ruby type-checker

npm_packages:  # node_packages
    - npm
    - neovim  # MIT
    - typescript  # Apache 2.0
    - babel-cli  # MIT
    - webpack  # MIT
    - hexo-cli  # MIT
    - yarn
    - prettier
    - markdownlint-cli
    - write-good

npm_packages_skip: []
npm_packages_extra: []

cabal_packages_skip: []
cabal_packages_extra: []
cabal_packages: []

stack_packages_skip: []
stack_packages_extra: []
stack_packages: []

stack_global_extra_deps: |
  extra-deps:
    - haskell-src-exts-1.20.3@sha256:83ae523bbec907a42c043de1f5bbf4c1554e7c3b898af07bb1ce6e80eaa282ec,4589

cargo_force_update: false
# https://github.com/rust-unofficial/awesome-rust#applications
cargo_packages:
  - crate: ddh
    git: https://github.com/darakian/ddh
  - git: https://github.com/lotabout/rargs
    crate: rargs
  - funzzy # https://github.com/cristianoliveira/funzzy
  - fw # https://github.com/brocode/fw
  - hx # Hexdump, https://github.com/sitkevij/hex
  # - runiq  # requires cmake
  - find-files  # https://github.com/vishaltelangre/ff
  # - cargo-modules  Requires nightly to *run* as of 0.4.4
