---
apt_packages_skip: []
apt_packages_extra: []

apt_packages_essential:
      # editors
    - neovim  # Apache 2.0
      # shell utilities / dev tools
    - build-essential
    - tmux  # ISC License
    - silversearcher-ag  # Apache 2.0
    - colordiff  # GPL v3
    - colortest
    - source-highlight  # GPL v3
    - pandoc  # GLP v2+ & BSD 3-clause & MIT & WTFPL (dzslides)
    - sshfs  # GPL v2
    - lftp  # GPL v3+
      # git
    - git  # GPL v2
    - git-lfs  # MIT
      # programming languages
    - openjdk-11-jdk  # GPL v2
    - ruby  # BDS 2-clause
    - ruby-dev

apt_packages:
      # editors
    - vim  # GPL-compatible
    # - vim-gtk
      # shell utilities / dev tools
    - linuxbrew-wrapper
    - shellcheck  # GPL v3
    - cloc  # GPL v2 & Artistic License
    - ghostscript
    - imagemagick  # Derived Apache 2.0
    - graphviz  # CPL 1.0
    - toilet  # command-line ascii art generator
    - libclang-dev  # 0.5gb :(
    - zlib1g-dev  # Required for cargo-update
    - libssl-dev  # Required for fw
    # - reptyer
    # - pdftk
      # git
    - gitk
    - tig
      # programming languages
    - ghc
    - cabal-install
    - perl
    - golang

install_homebrew: true
homebrew_install: https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh
homebrew_root: /home/linuxbrew/.linuxbrew
homebrew_bin: '{{ homebrew_root }}/Homebrew/bin/brew'
homebrew_bin_dir: '{{ homebrew_root }}/bin'

homebrew_packages:
    - git-credential-manager  # MIT
    - fish  # GPL v2 & LGPL v2, OpenBSD License, ISC, NetBSD
    - python  # GPL-compatible PSF; https://docs.python.org/3/license.html
    - fzf  # MIT
    - jq  # MIT
    - hub  # MIT
    - nvim
    - just  # github.com/casey/just
    - openssl@1.1

homebrew_packages_extra: []
homebrew_packages_skip: []

homebrew_links:
    - git-credential-manager
    - fish
    - just

pip_bin: '{{ homebrew_bin_dir }}/pip3'
pip_packages:
    - Pillow
    - PyYAML
    - Pygments
    - arrow
    - atomicwrites
    - attrs
    - beautifulsoup4
    - black
    - cached-property
    - cachetools
    - colorama
    - grip
    - more-itertools
    - mypy
    - neovim
    - numba
    - numpy
    - pep8
    - ptpython
    - pycodestyle
    - pylint
    - pynvim
    - pytest
    - python-dateutil
    - python-decouple
    - requests
    - termcolor
    - toml
    - unidecode
    - urllib3
    - virtualenv
    - wcwidth
    - youtube-dl
    - vim-vint  # vimscript lint: https://github.com/Kuniwak/vint

ruby_gems:
    - bundler
    - neovim  # MIT
    - uniscribe  # MIT
    - solargraph  # Ruby LSP
    # - sorbet-static  # Ruby type-checker

npm_packages:  # node_packages
    - npm
    - neovim  # MIT
    - typescript  # Apache 2.0
    - babel-cli  # MIT
    - webpack  # MIT
    - hexo-cli  # MIT
    - yarn
    - prettier
    - markdownlint-cli
    - write-good

npm_packages_skip: []
npm_packages_extra: []

cabal_packages_skip: []
cabal_packages_extra: []
cabal_packages:
  - happy  # required by other stuff, don't remove.
  - pointfree
  - hlint
  - apply-refact
  - hspec
  - hindent

stack_packages_skip: []
stack_packages_extra: []
stack_packages:
  - hdevtools
  - stylish-haskell

stack_global_extra_deps: |
  extra-deps:
    - haskell-src-exts-1.20.3@sha256:83ae523bbec907a42c043de1f5bbf4c1554e7c3b898af07bb1ce6e80eaa282ec,4589

cargo_force_update: false
# https://github.com/rust-unofficial/awesome-rust#applications
cargo_packages:
  - topgrade
  - crate: ddh
    git: https://github.com/darakian/ddh 
  - git: https://github.com/lotabout/rargs
    crate: rargs
  - bat  # requires libclang-dev; https://github.com/sharkdp/bat
  - bingrep # Binary introspection, https://github.com/m4b/bingrep
  - exa # ls replacement https://github.com/ogham/exa
  - fselect # "Find files with SQL-like queries" https://github.com/jhspetersson/fselect
  - funzzy # https://github.com/cristianoliveira/funzzy
  - fw # https://github.com/brocode/fw
  - hx # Hexdump, https://github.com/sitkevij/hex
  - hyperfine
  - ripgrep  # rg, https://github.com/BurntSushi/ripgrep
  # - runiq  # requires cmake
  - ruplacer
  - sd # Find-and-replacer, https://github.com/chmln/sd
  - find-files # https://github.com/vishaltelangre/ff
  - skim # Fuzzy finder, https://github.com/lotabout/skim
  - tokei # Cloc, https://github.com/XAMPPRocky/tokei
  - xsv # CSV data manipulation and analysis tool, https://github.com/BurntSushi/xsv
  - cargo-deps # Generates a dep graph, https://github.com/m-cat/cargo-deps
  - cargo-edit # https://github.com/killercup/cargo-edit
  - cargo-make # https://github.com/sagiegurari/cargo-make
  # - cargo-modules  Requires nightly to *run* as of 0.4.4
  # https://github.com/kbknapp/cargo-outdated
  - git: https://github.com/kbknapp/cargo-outdated
  - cargo-release # https://github.com/sunng87/cargo-release
  - cargo-tree # Dep tree. https://github.com/sfackler/cargo-tree
  - cargo-update # https://github.com/nabijaczleweli/cargo-update
  - cargo-watch # Watches source files, https://github.com/passcod/cargo-watch
