---
- name: Check for Linuxbrew fish
  stat:
      path: '{{ linuxbrew_fish }}'
  register: brew_fish
  changed_when: brew_fish.stat.exists and brew_fish.stat.executable

- name: Add Linuxbrew fish to /etc/shells
  when: brew_fish is changed
  lineinfile:
      path: /etc/shells
      line: '{{ linuxbrew_fish }}'

- name: Find fish
  command: which fish
  register: which_fish
  changed_when: which_fish.rc == 0

- name: chsh fish
  when: which_fish.changed
  become: true
  command: chsh {{ ansible_user_id }}
        --shell {{ which_fish.stdout }}
