---
- name: Check for Linuxbrew fish
  stat:
      path: '{{ linuxbrew_fish }}'
  register: brew_fish
  changed_when: brew_fish.stat.exists and brew_fish.stat.executable

- name: Add Linuxbrew fish to /etc/shells
  when: brew_fish is changed
  become: true
  lineinfile:
      path: /etc/shells
      line: '{{ linuxbrew_fish }}'

- name: chsh fish
  when: brew_fish is changed
  become: true
  command: chsh {{ ansible_user_id }}
        --shell {{ linuxbrew_fish }}

- name: Link win32yank for Neovim
  when: ansible_is_wsl
  become: true
  file:
      path: '{{ local_prefix }}/bin/win32yank.exe'
      src: '{{ neovim_win32yank }}'
      type: link
      mode: 0755
