---
- name: Clone dotfiles
  git:
      repo: '{{ dotfiles_repo.git }}'
      dest: '{{ dotfiles_repo.dest }}'
  register: dotfiles_clone

- name: Create dotfile directories
  loop: '{{ dotfiles }}'
  when: "'/' in item"
  file:
          path: '{{ ansible_user_dir }}/{{ item|dirname }}'
          state: directory

- name: Link dotfiles
  loop: '{{ dotfiles }}'
  file:
      path: '{{ ansible_user_dir }}/{{ item }}'
      src: '{{ dotfiles_repo.dest }}/{{ item }}'
      state: link
      force: true # clobber

- name: Find fish
  command: which fish
  failed_when: false
  register: which_fish
  changed_when: which_fish.rc == 0

- name: chsh fish
  when: which_fish.changed
  become: true
  command: chsh {{ ansible_user_id }}
        --shell {{ which_fish.stdout }}
