---
- name: Use bootstrapping .gitconfig
  become: true
  become_user: '{{ user }}'
  copy:
      src: bootstrap_gitconfig
      dest: '{{ ansible_user_dir }}/.gitconfig'

- name: Clone dotfiles
  become: true
  become_user: '{{ user }}'
  git:
      repo: '{{ dotfiles_repo.git }}'
      dest: '{{ dotfiles_repo.dest }}'
      update: false
  register: dotfiles_clone

- name: Delete bootstrapping .gitconfig
  file:
      state: absent
      path: '{{ ansible_user_dir }}/.gitconfig'

- name: Create dotfiles directories
  become: true
  become_user: '{{ user }}'
  loop: '{{ dotfiles + dotfiles_extra }}'
  when: "'/' in item and item not in dotfiles_skip"
  file:
      path: '{{ ansible_user_dir }}/{{ item|dirname }}'
      state: directory
      owner: '{{ user }}'

- name: Link dotfiles
  become: true
  become_user: '{{ user }}'
  loop: '{{ dotfiles + dotfiles_extra }}'
  when: item not in dotfiles_skip
  file:
      path: '{{ ansible_user_dir }}/{{ item }}'
      src: '{{ dotfiles_repo.dest }}/{{ item }}'
      state: link
      force: true # clobber
      owner: '{{ user }}'
