---
- name: Set umask 022
  command: umask 022

- name: Clone dotfiles
  become: true
  become_user: '{{ ansible_hostname }}'
  git:
      repo: '{{ dotfiles_repo.git }}'
      dest: '{{ dotfiles_repo.dest }}'
      update: false
  register: dotfiles_clone

- name: Create dotfile directories
  become: true
  become_user: '{{ ansible_hostname }}'
  loop: '{{ dotfiles }}'
  when: "'/' in item"
  file:
          path: '{{ ansible_user_dir }}/{{ item|dirname }}'
          state: directory

- name: Link dotfiles
  become: true
  become_user: '{{ ansible_hostname }}'
  loop: '{{ dotfiles }}'
  file:
      path: '{{ ansible_user_dir }}/{{ item }}'
      src: '{{ dotfiles_repo.dest }}/{{ item }}'
      state: link
      force: true # clobber

- name: Give self passwordless sudo
  become: true
  template:
      src: sudoers.jinja2
      dest: /etc/sudoers.d/{{ ansible_user_id }}
      mode: 0440
