---
- name: Give self passwordless sudo
  when: is_wsl|bool
  become: true
  template:
      src: sudoers.jinja2
      dest: /etc/sudoers.d/{{ ansible_user_id }}
      mode: 0440

- name: Ensure umask 022 in /etc/profile
  when: is_wsl|bool
  become: true
  lineinfile:
      path: /etc/profile
      line: umask 022

- name: Clone dotfiles
  become: true
  become_user: '{{ user }}'
  git:
      repo: '{{ dotfiles_repo.git }}'
      dest: '{{ dotfiles_repo.dest }}'
      update: false
  register: dotfiles_clone

- name: Create dotfile directories
  become: true
  become_user: '{{ user }}'
  loop: '{{ dotfiles }}'
  when: "'/' in item"
  file:
          path: '{{ ansible_user_dir }}/{{ item|dirname }}'
          state: directory

- name: Link dotfiles
  become: true
  become_user: '{{ user }}'
  loop: '{{ dotfiles }}'
  file:
      path: '{{ ansible_user_dir }}/{{ item }}'
      src: '{{ dotfiles_repo.dest }}/{{ item }}'
      state: link
      force: true # clobber

- name: Create other links
  become: true
  become_user: '{{ user }}'
  loop: '{{ symlinks }}'
  file:
      path: '{{ item.from }}'
      src: '{{ item.to }}'
      state: link
      force: true # clobber
