---
- name: Detect WSL
  tags:
      - config
  set_fact:
    is_wsl: '{{ "Microsoft" in lookup("file", "/proc/version") }}'

- name: Initial config
  tags:
      - config
  import_tasks: init.yml

- name: Bootstrap Git-Credential-Manager (github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux)
  tags:
      - packages
      - gcm
  when: bootstrap_gcm|bool
  import_tasks: packages/gcm.yml

- name: Clone / setup dotfiles
  tags:
      - config
      - dotfiles
  import_tasks: dotfiles.yml

- name: Install Vim config
  tags:
      - config
      - vim
  import_tasks: vim.yml

- name: Install packages
  tags:
      - packages
  import_tasks: packages/main.yml

- name: Perform final config
  tags:
      - config
      - final_config
  import_tasks: config.yml
