---
- name: Initial config
  tags:
          - config
  import_tasks: init.yml

- name: Install Linuxbrew
  tags:
      - packages
      - brew
      - homebrew
      - linuxbrew
  import_tasks: packages/linuxbrew.yml

- name: Install packages & other software
  tags:
          - packages
  import_tasks: packages/managers.yml

- name: Install Vim config
  tags:
          - config
          - vim
  import_tasks: vim.yml

- name: Install Rust
  tags:
          - packages
          - rust
  import_tasks: packages/rust.yml

- name: Install Talisman (github.com/thoughtworks/talisman)
  tags:
      - packages
      - talisman
  import_tasks: packages/talisman.yml

- name: Install hexd (github.com/FireyFly/hexd)
  tags:
      - packages
      - hexd
  import_tasks: packages/hexd.yml

- name: Install pixd (github.com/FireyFly/pixd)
  tags:
      - packages
      - pixd
  import_tasks: packages/pixd.yml

- name: Install TeX Live
  tags:
      - packages
      - tex
  become: true
  apt:
          package: texlive
