---
- name: Detect WSL
  set_fact:
    is_wsl: '{{ "WSL_DISTRO_NAME" in ansible_env }}'

- name: Initial config
  tags:
          - config
  import_tasks: init.yml

- name: Install Vim config
  tags:
          - config
          - vim
  import_tasks: vim.yml

- name: Install packages
  tags:
      - packages
  import_tasks: packages/main.yml

- name: Perform final config
  tags:
      - config
  import_tasks: config.yml
