---
- name: Clone vimfiles repository
  register: vimfiles_git
  become: true
  become_user: '{{ user }}'
  git:
      repo: '{{ vimfiles.repo }}'
      dest: '{{ vimfiles.dest }}'

- name: Link nvim config to vimfiles
  become: true
  become_user: '{{ user }}'
  file:
          path: '{{ ansible_user_dir }}/.config/nvim'
          src: '{{ vimfiles.dest }}'
          state: link
