---
- name: Install Dhall
  become: true
  loop: '{{ dhall_packages }}'
  unarchive:
    src: '{{ dhall_url_prefix }}/{{ item.name }}-{{ item.ver }}-{{ dhall_ext }}'
    creates: /usr/bin/{{ item.creates|default(item.name) }}
    dest: /usr
    keep_newer: true
    remote_src: true
