---
- name: Check for fd
  stat:
    path: '{{ fd_bin }}'
  register: fd_stat
  changed_when: not (fd_stat.stat.exists and fd_stat.stat.executable)

- name: Install fd
  when: fd_stat is changed
  become: true
  apt:
    deb: '{{ fd_deb }}'
