---
- name: Check for fd
  stat:
    path: '{{ fd_bin }}'
  register: fd_stat
  changed_when: not (fd_stat.stat.exists and fd_stat.stat.executable)

- name: Install fd
  when: fd_stat|changed
  block:
    - name: Create temporary file
      register: tmp_fd
      tempfile:
        suffix: .deb

    - name: Download fd
      get_url:
        url: '{{ fd_url }}'
        dest: '{{ tmp_fd.path }}'

    - name: Install fd
      become: true
      command: dpkg -i {{ tmp_fd.path }}
