---
- name: Check for fisher (github.com/jorgebucaran/fisher)
  register: fisher_stat
  stat:
          path: '{{ fisher }}'
  changed_when: not fisher_stat.stat.exists

- name: Install fisher (github.com/jorgebucaran/fisher)
  when: fisher_stat is changed
  get_url:
      url: '{{ fisher_url }}'
      dest: '{{ fisher }}'

- name: Update fisher plugins
  when: fisher_stat is changed
  command: '{{ linuxbrew_fish }} -c fisher'
