---
- name: Check for fisher (github.com/jorgebucaran/fisher)
  register: fisher_stat
  stat:
          path: '{{ fisher }}'
  changed_when: not fisher_stat.stat.exists

- name: Install fisher (github.com/jorgebucaran/fisher)
  when: fisher_stat is changed
  command: curl {{ fisher_url }} --create-dirs -sLo {{ fisher }}
