---
- name: Check for Microsoft Git Credential Manager
  stat:
      path: '{{ gcm_shim_dest }}'
  register: gcm_stat
  changed_when: not (gcm_stat.stat.exists and gcm_stat.stat.executable)

- name: Install Microsoft Git Credential Manager
  become: true
  when: gcm_stat.changed
  block:
      - name: Download GCM
        get_url:
            url: '{{ gcm_url }}'
            dest: '{{ gcm_dest }}'

      - name: Add GCM shim
        template:
            src: gcm.sh.jinja2
            dest: '{{ gcm_shim_dest }}'
            mode: 0755
