---
- name: Install Linuxbrew packages
  when: install_homebrew|bool
  become: true
  become_user: '{{ user }}'
  loop: '{{ packages }}'
  vars:
      # Spurious error
      # https://github.com/microsoft/WSL/issues/1838
      nice_warning: 'nice: cannot set niceness: Permission denied'
  homebrew:
      state: latest
      package: '{{ item }}'
      path: '{{ homebrew_bin_dir }}'
  register: brew_install
  failed_when: brew_install is failed
          and (brew_install.msg|replace(nice_warning, '')).strip() != ''
