---
- name: Install Fish plugins
  when: false  # NOTE: this task is disabled until WSL gets some bugs fixed
  tags:
          - fish
          - packages
  import_tasks: fish.yml

- name: Install Tmux plugins
  tags:
          - tmux
          - packages
  import_tasks: tmux.yml

- name: Install Linuxbrew
  tags:
      - packages
      - brew
      - homebrew
      - linuxbrew
  import_tasks: linuxbrew.yml

- name: Install packages & other software
  tags:
          - packages
  import_tasks: managers.yml

- name: Update fisher plugins
  when: fisher_stat is changed
  command: '{{ linuxbrew_fish }} -c fisher'

- name: Install Rust
  tags:
          - packages
          - rust
  import_tasks: rust.yml

- name: Install Talisman (github.com/thoughtworks/talisman)
  tags:
      - packages
      - talisman
  import_tasks: talisman.yml

- name: Install hexd (github.com/FireyFly/hexd)
  tags:
      - packages
      - hexd
  import_tasks: hexd.yml

- name: Install pixd (github.com/FireyFly/pixd)
  tags:
      - packages
      - pixd
  import_tasks: pixd.yml

- name: Install TeX Live
  tags:
      - packages
      - tex
  become: true
  apt:
          package: texlive
