---
- name: Install apt packages (essential)
  become: true
  loop: '{{ apt_packages_essential }}'
  when: item not in apt_packages_skip
  apt:
      package: '{{ item }}'

- name: Install apt packages
  become: true
  loop: '{{ apt_packages + apt_packages_extra }}'
  when: item not in apt_packages_skip
  apt:
      package: '{{ item }}'

- name: Install Linuxbrew packages
  tags:
      - brew
      - homebrew
      - linuxbrew
  when: install_homebrew|bool
  become: true
  become_user: '{{ user }}'
  loop: '{{ packages }}'
  vars:
      packages: '{{ homebrew_packages + homebrew_packages_extra }}'
      # Spurious error
      # https://github.com/microsoft/WSL/issues/1838
      nice_warning: 'nice: cannot set niceness: Permission denied'
  homebrew:
      state: latest
      package: '{{ item }}'
      path: '{{ homebrew_bin_dir }}'
  register: brew_install
  failed_when: brew_install is failed
          and (brew_install.msg|replace(nice_warning, '')).strip() != ''

- name: Link Linuxbrew binaries to /usr/local/bin
  tags:
      - packages
      - brew
      - homebrew
      - linuxbrew
  when: install_homebrew|bool
  loop: '{{ homebrew_links }}'
  become: true
  file:
      state: link
      src: '{{ homebrew_bin_dir }}/{{ item }}'
      path: '/usr/local/bin/{{ item }}'
      mode: 0755

- name: Install pip packages
  become: true
  pip:
      executable: '{{ pip_bin }}'
      name: '{{ pip_packages }}'
      state: latest

- name: Install Ruby Gems
  become: true
  loop: '{{ ruby_gems }}'
  gem:
      name: '{{ item }}'
      state: latest
      user_install: false

- name: Install Node (npm) packages
  become: '{{ npm_install_become|bool }}'
  tags:
      - node
      - npm
  loop: '{{ npm_packages + npm_packages_extra }}'
  when: item not in npm_packages_skip
  npm:
      executable: '{{ npm_bin }}'
      global: true
      name: '{{ item }}'
      state: latest

- name: Install Vim plugins
  become: true
  become_user: '{{ user }}'
  shell: "yes '\n' | vim +PlugInstall +qall!"
