---
- name: Check for MikTeX mpm
  stat:
    path: '{{ miktex_mpm_bin }}'
  register: mpm_stat
  changed_when: not mpm_stat.stat.exists

- name: Install MikTeX from Aptitude
  when: mpm_stat is changed
  block:
    - name: Add MikTeX GPG key
      become: true
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: '{{ miktex_gpg_key }}'

    - name: Add MikTeX repository
      become: true
      apt_repository:
        filename: miktex
        repo: '{{ miktex_apt_repo }}'

    - name: Install MikTeX
      become: true
      apt:
        package: miktex

    - name: Upgrade to package-level {{ miktex_package_level }}
      command: 'mpm --admin --upgrade --package-level={{ miktex_package_level }}'

- name: Create local root directory
  file:
    path: '{{ miktex_local_root }}'
    state: directory

- name: Clone rebeccastyle
  git:
    repo: '{{ rebeccastyle_repo.git }}'
    dest: '{{ rebeccastyle_repo.dest }}'

- name: Install rebeccastyle
  command: make install
  args:
    chdir: '{{ rebeccastyle_repo.dest }}'

- name: Register user TEXMF root {{ user_texmf_root }}
  become: true
  command: initexmf --admin --verbose --user-roots={{ user_texmf_root }}

- name: Refresh FNDB (root)
  become: true
  command: initexmf --admin --verbose --update-fndb

- name: Refresh FNDB (user)
  command: initexmf --verbose --update-fndb
