---
- name: Check for Git templates
  stat:
      path: '{{ pre_commit_tpl }}'
  register: pre_commit
  changed_when: not pre_commit.stat.exists

- name: Check for Talisman pre-commit hook
  when: pre_commit is not changed
  register: talisman_grep
  command: grep talisman {{ pre_commit_tpl }}
  failed_when: talisman_grep.rc not in [0, 1]
  changed_when: talisman_grep.rc == 1

- name: Install github.com/thoughtworks/talisman
  when: pre_commit is changed or talisman_grep is changed
  block:
    - name: Create temporary file
      register: tmp_bash
      tempfile:
          suffix: .bash

    - name: Download Talisman
      get_url:
          url: '{{ talisman_url }}'
          dest: '{{ tmp_bash.path }}'

    - name: Install Talisman
      shell: "yes '\n' | bash {{ tmp_bash.path }}"
